'use server';
/**
 * @fileOverview AI-driven profile blurb generator.
 *
 * - generateProfileBlurb - A function that generates a profile blurb.
 * - GenerateProfileBlurbInput - The input type for the generateProfileBlurb function.
 * - GenerateProfileBlurbOutput - The return type for the generateProfileBlurb function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProfileBlurbInputSchema = z.object({
  interests: z
    .string()
    .describe('A list of interests of the user, separated by commas.'),
});
export type GenerateProfileBlurbInput = z.infer<typeof GenerateProfileBlurbInputSchema>;

const GenerateProfileBlurbOutputSchema = z.object({
  blurb: z.string().describe('A short, engaging profile blurb generated by AI.'),
});
export type GenerateProfileBlurbOutput = z.infer<typeof GenerateProfileBlurbOutputSchema>;

export async function generateProfileBlurb(
  input: GenerateProfileBlurbInput
): Promise<GenerateProfileBlurbOutput> {
  return generateProfileBlurbFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProfileBlurbPrompt',
  input: {schema: GenerateProfileBlurbInputSchema},
  output: {schema: GenerateProfileBlurbOutputSchema},
  prompt: `You are a profile writing assistant. Generate a short and engaging profile blurb based on the user's interests.

Interests: {{{interests}}}`,
});

const generateProfileBlurbFlow = ai.defineFlow(
  {
    name: 'generateProfileBlurbFlow',
    inputSchema: GenerateProfileBlurbInputSchema,
    outputSchema: GenerateProfileBlurbOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
